services:
  - type: web
    name: scalping-bot
    env: python
    runtime: python
    pythonVersion: 3.11.8
    buildCommand: ""
    startCommand: python main.py
    region: frankfurt
    plan: free
    branch: main
    autoDeploy: true
    envVars:
      - fromGroup: scalping-bot-env
